#include "internal.h"

#include <string.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif

static const char schema_sql[] =
    "CREATE TABLE metadata (\n"
    "  key TEXT PRIMARY KEY,\n"
    "  value TEXT NOT NULL\n"
    ");\n"
    "CREATE TABLE schema_migrations (\n"
    "  version INTEGER PRIMARY KEY,\n"
    "  name TEXT NOT NULL UNIQUE,\n"
    "  checksum TEXT NOT NULL CHECK(length(checksum)=64),\n"
    "  applied_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now'))\n"
    ");\n"
    "CREATE TABLE db_operations (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  occurred_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now')),\n"
    "  command TEXT NOT NULL,\n"
    "  entity_type TEXT,\n"
    "  entity_id INTEGER,\n"
    "  details_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(details_json) "
    "AND json_type(details_json)='object')\n"
    ");\n"
    "CREATE TABLE source_units (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  corpus_slug TEXT NOT NULL,\n"
    "  unit_key TEXT NOT NULL,\n"
    "  unit_type TEXT NOT NULL CHECK(unit_type IN('chapter','appendix')),\n"
    "  title TEXT NOT NULL CHECK(length(trim(title))>0),\n"
    "  source_path TEXT NOT NULL UNIQUE,\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  start_page INTEGER NOT NULL CHECK(start_page>0),\n"
    "  end_page INTEGER NOT NULL CHECK(end_page>=start_page),\n"
    "  start_line INTEGER NOT NULL DEFAULT 1 CHECK(start_line>0),\n"
    "  end_line INTEGER NOT NULL CHECK(end_line>=start_line),\n"
    "  include_in_quizzes INTEGER NOT NULL CHECK(include_in_quizzes IN(0,1)),\n"
    "  included_reason TEXT NOT NULL CHECK(length(trim(included_reason))>0),\n"
    "  content_sha256 TEXT NOT NULL CHECK(length(content_sha256)=64),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  UNIQUE(corpus_slug,unit_key),\n"
    "  UNIQUE(corpus_slug,position)\n"
    ");\n"
    "CREATE TABLE source_sections (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  unit_id INTEGER NOT NULL REFERENCES source_units(id) ON DELETE CASCADE,\n"
    "  section_key TEXT NOT NULL,\n"
    "  title TEXT NOT NULL,\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  start_page INTEGER NOT NULL CHECK(start_page>0),\n"
    "  end_page INTEGER NOT NULL CHECK(end_page>=start_page),\n"
    "  start_line INTEGER NOT NULL CHECK(start_line>0),\n"
    "  end_line INTEGER NOT NULL CHECK(end_line>=start_line),\n"
    "  is_summary INTEGER NOT NULL DEFAULT 0 CHECK(is_summary IN(0,1)),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  UNIQUE(unit_id,section_key),\n"
    "  UNIQUE(unit_id,position)\n"
    ");\n"
    "CREATE TABLE concepts (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  unit_id INTEGER NOT NULL REFERENCES source_units(id) ON DELETE CASCADE,\n"
    "  primary_section_id INTEGER NOT NULL REFERENCES source_sections(id),\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  name TEXT NOT NULL CHECK(length(trim(name))>0),\n"
    "  description TEXT NOT NULL CHECK(length(trim(description))>0),\n"
    "  importance TEXT NOT NULL CHECK(importance IN('core','important','supporting')),\n"
    "  theory_required INTEGER NOT NULL CHECK(theory_required IN(0,1)),\n"
    "  application_required INTEGER NOT NULL CHECK(application_required IN(0,1)),\n"
    "  code_required INTEGER NOT NULL CHECK(code_required IN(0,1)),\n"
    "  semantics_required INTEGER NOT NULL CHECK(semantics_required IN(0,1)),\n"
    "  source_pages TEXT NOT NULL,\n"
    "  source_line_start INTEGER NOT NULL CHECK(source_line_start>0),\n"
    "  source_line_end INTEGER NOT NULL CHECK(source_line_end>=source_line_start),\n"
    "  justification TEXT NOT NULL CHECK(length(trim(justification))>0),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  UNIQUE(unit_id,position),\n"
    "  UNIQUE(id,unit_id)\n"
    ");\n"
    "CREATE TABLE concept_sources (\n"
    "  concept_id INTEGER NOT NULL REFERENCES concepts(id) ON DELETE CASCADE,\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  section_id INTEGER NOT NULL REFERENCES source_sections(id),\n"
    "  source_pages TEXT NOT NULL,\n"
    "  source_line_start INTEGER NOT NULL CHECK(source_line_start>0),\n"
    "  source_line_end INTEGER NOT NULL CHECK(source_line_end>=source_line_start),\n"
    "  role TEXT NOT NULL CHECK(role IN('primary','supporting')),\n"
    "  justification TEXT NOT NULL CHECK(length(trim(justification))>0),\n"
    "  PRIMARY KEY(concept_id,position)\n"
    ");\n"
    "CREATE TABLE question_bank (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  unit_id INTEGER NOT NULL,\n"
    "  concept_id INTEGER NOT NULL,\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  earliest_checkpoint REAL NOT NULL CHECK(earliest_checkpoint IN(0.25,0.5,0.75,1.0)),\n"
    "  question_type TEXT NOT NULL CHECK(question_type IN('recall','application',"
    "'misconception','relationship','example','code_reading','code_writing','debugging')),\n"
    "  response_format TEXT NOT NULL CHECK(response_format IN('free_response',"
    "'multiple_choice','code_response')),\n"
    "  prompt TEXT NOT NULL CHECK(length(trim(prompt))>0),\n"
    "  options_json TEXT CHECK(options_json IS NULL OR (json_valid(options_json) "
    "AND json_type(options_json)='array')),\n"
    "  expected_answer TEXT NOT NULL CHECK(length(trim(expected_answer))>0),\n"
    "  grading_criteria_json TEXT NOT NULL CHECK(json_valid(grading_criteria_json) "
    "AND json_type(grading_criteria_json)='array' AND "
    "json_array_length(grading_criteria_json)>0),\n"
    "  answer_justification TEXT NOT NULL CHECK(length(trim(answer_justification))>0),\n"
    "  source_section TEXT NOT NULL CHECK(length(trim(source_section))>0),\n"
    "  source_pages TEXT NOT NULL,\n"
    "  source_line_start INTEGER NOT NULL CHECK(source_line_start>0),\n"
    "  source_line_end INTEGER NOT NULL CHECK(source_line_end>=source_line_start),\n"
    "  body_verified INTEGER NOT NULL DEFAULT 1 CHECK(body_verified=1),\n"
    "  active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),\n"
    "  revision INTEGER NOT NULL DEFAULT 1 CHECK(revision>0),\n"
    "  supersedes_question_id INTEGER REFERENCES question_bank(id),\n"
    "  created_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now')),\n"
    "  updated_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now')),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  FOREIGN KEY(concept_id,unit_id) REFERENCES concepts(id,unit_id) ON DELETE CASCADE,\n"
    "  UNIQUE(unit_id,position),\n"
    "  CHECK((response_format='multiple_choice' AND options_json IS NOT NULL "
    "AND json_array_length(options_json) BETWEEN 3 AND 5) OR "
    "(response_format IN('free_response','code_response') AND options_json IS NULL))\n"
    ");\n"
    "CREATE TABLE question_sources (\n"
    "  question_id INTEGER NOT NULL REFERENCES question_bank(id) ON DELETE CASCADE,\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  section_id INTEGER NOT NULL REFERENCES source_sections(id),\n"
    "  source_pages TEXT NOT NULL,\n"
    "  source_line_start INTEGER NOT NULL CHECK(source_line_start>0),\n"
    "  source_line_end INTEGER NOT NULL CHECK(source_line_end>=source_line_start),\n"
    "  role TEXT NOT NULL CHECK(role IN('primary','supporting')),\n"
    "  justification TEXT NOT NULL CHECK(length(trim(justification))>0),\n"
    "  PRIMARY KEY(question_id,position)\n"
    ");\n"
    "CREATE TABLE tags (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  kind TEXT NOT NULL COLLATE NOCASE CHECK(length(trim(kind))>0),\n"
    "  name TEXT NOT NULL COLLATE NOCASE CHECK(length(trim(name))>0),\n"
    "  description TEXT NOT NULL,\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  UNIQUE(kind,name)\n"
    ");\n"
    "CREATE TABLE question_tags (\n"
    "  question_id INTEGER NOT NULL REFERENCES question_bank(id) ON DELETE CASCADE,\n"
    "  tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,\n"
    "  PRIMARY KEY(question_id,tag_id)\n"
    ");\n"
    "CREATE TABLE tag_aliases (\n"
    "  tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,\n"
    "  alias TEXT NOT NULL COLLATE NOCASE UNIQUE CHECK(length(trim(alias))>0),\n"
    "  PRIMARY KEY(tag_id,alias)\n"
    ");\n"
    "CREATE TABLE tag_relations (\n"
    "  parent_tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,\n"
    "  child_tag_id INTEGER NOT NULL REFERENCES tags(id) ON DELETE CASCADE,\n"
    "  relation_type TEXT NOT NULL DEFAULT 'contains' CHECK(length(trim(relation_type))>0),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  PRIMARY KEY(parent_tag_id,child_tag_id,relation_type),\n"
    "  CHECK(parent_tag_id<>child_tag_id)\n"
    ");\n"
    "CREATE TABLE quiz_templates (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  scope_type TEXT NOT NULL CHECK(scope_type IN('checkpoint','final','topic','theme')),\n"
    "  title TEXT NOT NULL CHECK(length(trim(title))>0),\n"
    "  unit_id INTEGER REFERENCES source_units(id) ON DELETE CASCADE,\n"
    "  tag_id INTEGER REFERENCES tags(id) ON DELETE CASCADE,\n"
    "  checkpoint REAL CHECK(checkpoint IN(0.25,0.5,0.75,1.0)),\n"
    "  selection_policy TEXT NOT NULL,\n"
    "  active INTEGER NOT NULL DEFAULT 1 CHECK(active IN(0,1)),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  CHECK((scope_type='checkpoint' AND unit_id IS NOT NULL AND tag_id IS NULL "
    "AND checkpoint IN(0.25,0.5,0.75)) OR "
    "(scope_type='final' AND unit_id IS NOT NULL AND tag_id IS NULL AND checkpoint=1.0) OR "
    "(scope_type IN('topic','theme') AND tag_id IS NOT NULL AND unit_id IS NULL "
    "AND checkpoint IS NULL))\n"
    ");\n"
    "CREATE UNIQUE INDEX quiz_templates_identity ON quiz_templates("
    "scope_type,ifnull(unit_id,0),ifnull(tag_id,0),ifnull(checkpoint,0));\n"
    "CREATE TABLE quiz_template_questions (\n"
    "  template_id INTEGER NOT NULL REFERENCES quiz_templates(id) ON DELETE CASCADE,\n"
    "  question_id INTEGER NOT NULL REFERENCES question_bank(id) ON DELETE CASCADE,\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  PRIMARY KEY(template_id,question_id),\n"
    "  UNIQUE(template_id,position)\n"
    ");\n"
    "CREATE TABLE quiz_sessions (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  created_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now')),\n"
    "  completed_at TEXT,\n"
    "  scope_type TEXT NOT NULL CHECK(scope_type IN('chapter_checkpoint','chapter_final',"
    "'topic','theme')),\n"
    "  source_unit_id INTEGER REFERENCES source_units(id),\n"
    "  scope_label TEXT NOT NULL,\n"
    "  state TEXT NOT NULL CHECK(state "
    "IN('planned','in_progress','paused','completed','abandoned')),\n"
    "  coverage_policy TEXT NOT NULL DEFAULT 'balanced_weighted',\n"
    "  delivery TEXT NOT NULL DEFAULT 'cli',\n"
    "  template_id INTEGER REFERENCES quiz_templates(id),\n"
    "  base_question_count INTEGER NOT NULL CHECK(base_question_count>=0),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  CHECK((scope_type IN('chapter_checkpoint','chapter_final') AND source_unit_id IS NOT NULL) "
    "OR scope_type IN('topic','theme')),\n"
    "  CHECK((state IN('completed','abandoned') AND completed_at IS NOT NULL) OR "
    "(state NOT IN('completed','abandoned') AND completed_at IS NULL))\n"
    ");\n"
    "CREATE TABLE quiz_objectives (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  quiz_id INTEGER NOT NULL REFERENCES quiz_sessions(id) ON DELETE CASCADE,\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  section_title TEXT NOT NULL,\n"
    "  concept TEXT NOT NULL,\n"
    "  importance TEXT NOT NULL CHECK(importance IN('core','important','supporting')),\n"
    "  source_pages TEXT NOT NULL,\n"
    "  source_line_start INTEGER NOT NULL CHECK(source_line_start>0),\n"
    "  source_line_end INTEGER NOT NULL CHECK(source_line_end>=source_line_start),\n"
    "  justification TEXT NOT NULL,\n"
    "  concept_id INTEGER REFERENCES concepts(id),\n"
    "  UNIQUE(quiz_id,position),\n"
    "  UNIQUE(id,quiz_id)\n"
    ");\n"
    "CREATE TABLE quiz_questions (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  quiz_id INTEGER NOT NULL,\n"
    "  objective_id INTEGER NOT NULL,\n"
    "  position INTEGER NOT NULL CHECK(position>0),\n"
    "  origin TEXT NOT NULL CHECK(origin IN('base','follow_up')),\n"
    "  question_type TEXT NOT NULL CHECK(question_type IN('recall','application',"
    "'misconception','relationship','example','code_reading','code_writing','debugging')),\n"
    "  response_format TEXT NOT NULL CHECK(response_format IN('free_response',"
    "'multiple_choice','code_response')),\n"
    "  prompt TEXT NOT NULL,\n"
    "  options_json TEXT CHECK(options_json IS NULL OR (json_valid(options_json) "
    "AND json_type(options_json)='array')),\n"
    "  expected_answer TEXT NOT NULL,\n"
    "  grading_criteria_json TEXT NOT NULL CHECK(json_valid(grading_criteria_json) "
    "AND json_type(grading_criteria_json)='array' AND "
    "json_array_length(grading_criteria_json)>0),\n"
    "  answer_justification TEXT NOT NULL,\n"
    "  source_section TEXT NOT NULL,\n"
    "  source_pages TEXT NOT NULL,\n"
    "  source_line_start INTEGER NOT NULL CHECK(source_line_start>0),\n"
    "  source_line_end INTEGER NOT NULL CHECK(source_line_end>=source_line_start),\n"
    "  state TEXT NOT NULL CHECK(state IN('planned','asked','deferred','answered','retired')),\n"
    "  asked_at TEXT,\n"
    "  bank_question_id INTEGER REFERENCES question_bank(id),\n"
    "  FOREIGN KEY(quiz_id) REFERENCES quiz_sessions(id) ON DELETE CASCADE,\n"
    "  FOREIGN KEY(objective_id,quiz_id) REFERENCES quiz_objectives(id,quiz_id) ON DELETE "
    "CASCADE,\n"
    "  UNIQUE(quiz_id,position),\n"
    "  CHECK((response_format='multiple_choice' AND options_json IS NOT NULL "
    "AND json_array_length(options_json) BETWEEN 3 AND 5) OR "
    "(response_format IN('free_response','code_response') AND options_json IS NULL))\n"
    ");\n"
    "CREATE UNIQUE INDEX quiz_questions_one_asked ON quiz_questions(quiz_id) WHERE state='asked';\n"
    "CREATE TABLE quiz_responses (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  question_id INTEGER NOT NULL REFERENCES quiz_questions(id) ON DELETE CASCADE,\n"
    "  attempt_number INTEGER NOT NULL CHECK(attempt_number>0),\n"
    "  answered_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now')),\n"
    "  answer TEXT NOT NULL CHECK(length(trim(answer))>0),\n"
    "  assessment TEXT NOT NULL CHECK(assessment IN('correct','partially_correct','incorrect')),\n"
    "  feedback TEXT NOT NULL CHECK(length(trim(feedback))>0),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  UNIQUE(question_id,attempt_number)\n"
    ");\n"
    "CREATE TABLE learning_records (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  created_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now')),\n"
    "  topic TEXT NOT NULL CHECK(length(trim(topic))>0),\n"
    "  state TEXT NOT NULL CHECK(state IN('learning','review','mastered','needs_correction')),\n"
    "  evidence TEXT NOT NULL CHECK(length(trim(evidence))>0),\n"
    "  next_step TEXT,\n"
    "  source_type TEXT NOT NULL DEFAULT 'conversation' "
    "CHECK(source_type IN('conversation','quiz','code_review')),\n"
    "  quiz_id INTEGER REFERENCES quiz_sessions(id),\n"
    "  quiz_response_id INTEGER REFERENCES quiz_responses(id),\n"
    "  metadata_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(metadata_json) "
    "AND json_type(metadata_json)='object'),\n"
    "  CHECK((source_type='quiz' AND quiz_id IS NOT NULL) OR "
    "(source_type<>'quiz' AND quiz_id IS NULL AND quiz_response_id IS NULL))\n"
    ");\n"
    "CREATE TABLE quiz_events (\n"
    "  id INTEGER PRIMARY KEY,\n"
    "  quiz_id INTEGER NOT NULL REFERENCES quiz_sessions(id) ON DELETE CASCADE,\n"
    "  question_id INTEGER REFERENCES quiz_questions(id) ON DELETE CASCADE,\n"
    "  response_id INTEGER REFERENCES quiz_responses(id) ON DELETE CASCADE,\n"
    "  event_type TEXT NOT NULL,\n"
    "  reason TEXT,\n"
    "  payload_json TEXT NOT NULL DEFAULT '{}' CHECK(json_valid(payload_json) "
    "AND json_type(payload_json)='object'),\n"
    "  created_at TEXT NOT NULL DEFAULT(strftime('%Y-%m-%dT%H:%M:%fZ','now'))\n"
    ");\n"
    "CREATE TRIGGER question_bank_mcq_insert BEFORE INSERT ON question_bank\n"
    "WHEN NEW.response_format='multiple_choice' AND (SELECT count(*) FROM "
    "json_each(NEW.options_json) WHERE value=NEW.expected_answer)<>1\n"
    "BEGIN SELECT raise(ABORT,'multiple-choice answer must match exactly one option'); END;\n"
    "CREATE TRIGGER question_bank_mcq_update BEFORE UPDATE OF response_format,options_json,"
    "expected_answer ON question_bank\n"
    "WHEN NEW.response_format='multiple_choice' AND (SELECT count(*) FROM "
    "json_each(NEW.options_json) WHERE value=NEW.expected_answer)<>1\n"
    "BEGIN SELECT raise(ABORT,'multiple-choice answer must match exactly one option'); END;\n"
    "CREATE TRIGGER quiz_questions_mcq_insert BEFORE INSERT ON quiz_questions\n"
    "WHEN NEW.response_format='multiple_choice' AND (SELECT count(*) FROM "
    "json_each(NEW.options_json) WHERE value=NEW.expected_answer)<>1\n"
    "BEGIN SELECT raise(ABORT,'snapshot answer must match exactly one option'); END;\n"
    "CREATE TRIGGER terminal_objective_insert BEFORE INSERT ON quiz_objectives\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_sessions WHERE id=NEW.quiz_id "
    "AND state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz snapshot is immutable'); END;\n"
    "CREATE TRIGGER terminal_objective_update BEFORE UPDATE ON quiz_objectives\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_sessions WHERE id IN(OLD.quiz_id,NEW.quiz_id) "
    "AND state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz snapshot is immutable'); END;\n"
    "CREATE TRIGGER terminal_objective_delete BEFORE DELETE ON quiz_objectives\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_sessions WHERE id=OLD.quiz_id "
    "AND state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz snapshot is immutable'); END;\n"
    "CREATE TRIGGER terminal_question_insert BEFORE INSERT ON quiz_questions\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_sessions WHERE id=NEW.quiz_id "
    "AND state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz snapshot is immutable'); END;\n"
    "CREATE TRIGGER terminal_question_update BEFORE UPDATE ON quiz_questions\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_sessions WHERE id IN(OLD.quiz_id,NEW.quiz_id) "
    "AND state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz snapshot is immutable'); END;\n"
    "CREATE TRIGGER terminal_question_delete BEFORE DELETE ON quiz_questions\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_sessions WHERE id=OLD.quiz_id "
    "AND state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz snapshot is immutable'); END;\n"
    "CREATE TRIGGER terminal_response_insert BEFORE INSERT ON quiz_responses\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_questions q JOIN quiz_sessions s ON s.id=q.quiz_id "
    "WHERE q.id=NEW.question_id AND s.state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz responses are immutable'); END;\n"
    "CREATE TRIGGER terminal_response_update BEFORE UPDATE ON quiz_responses\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_questions q JOIN quiz_sessions s ON s.id=q.quiz_id "
    "WHERE q.id IN(OLD.question_id,NEW.question_id) AND s.state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz responses are immutable'); END;\n"
    "CREATE TRIGGER terminal_response_delete BEFORE DELETE ON quiz_responses\n"
    "WHEN EXISTS(SELECT 1 FROM quiz_questions q JOIN quiz_sessions s ON s.id=q.quiz_id "
    "WHERE q.id=OLD.question_id AND s.state IN('completed','abandoned'))\n"
    "BEGIN SELECT raise(ABORT,'terminal quiz responses are immutable'); END;\n"
    "CREATE INDEX concept_sources_section ON concept_sources(section_id,concept_id);\n"
    "CREATE INDEX question_bank_unit_checkpoint ON question_bank(unit_id,active,"
    "earliest_checkpoint,position);\n"
    "CREATE INDEX question_sources_section ON question_sources(section_id,question_id);\n"
    "CREATE INDEX question_tags_tag ON question_tags(tag_id,question_id);\n"
    "CREATE INDEX tag_relations_child ON tag_relations(child_tag_id,relation_type);\n"
    "CREATE INDEX quiz_templates_scope ON "
    "quiz_templates(scope_type,unit_id,tag_id,checkpoint,active);\n"
    "CREATE INDEX quiz_sessions_state ON quiz_sessions(state,scope_type,template_id);\n"
    "CREATE INDEX quiz_questions_quiz ON quiz_questions(quiz_id,state,position);\n"
    "CREATE INDEX quiz_questions_bank ON quiz_questions(bank_question_id);\n"
    "CREATE INDEX learning_records_topic_created ON learning_records(topic COLLATE NOCASE,"
    "created_at DESC,id DESC);\n"
    "CREATE INDEX db_operations_command ON db_operations(command,occurred_at DESC);\n"
    "CREATE INDEX quiz_events_quiz_created ON quiz_events(quiz_id,created_at,id);\n"
    "CREATE INDEX quiz_events_question ON quiz_events(question_id,id);\n"
    "CREATE VIEW tag_catalog AS\n"
    "SELECT t.id,t.kind,t.name,t.description,\n"
    " count(DISTINCT qt.question_id) AS question_count,\n"
    " count(DISTINCT CASE WHEN qb.active=1 THEN qt.question_id END) AS active_question_count\n"
    "FROM tags t LEFT JOIN question_tags qt ON qt.tag_id=t.id\n"
    "LEFT JOIN question_bank qb ON qb.id=qt.question_id GROUP BY t.id;\n"
    "CREATE VIEW source_coverage AS\n"
    "SELECT su.id AS unit_id,su.corpus_slug,su.unit_key,su.title,su.include_in_quizzes,\n"
    " (SELECT count(*) FROM concepts c WHERE c.unit_id=su.id) AS concept_count,\n"
    " (SELECT count(*) FROM question_bank q WHERE q.unit_id=su.id AND q.active=1) "
    "AS question_count,\n"
    " (SELECT count(*) FROM question_bank q WHERE q.unit_id=su.id AND q.active=1 "
    "AND q.response_format='free_response') AS free_response_count,\n"
    " (SELECT count(*) FROM question_bank q WHERE q.unit_id=su.id AND q.active=1 "
    "AND q.response_format='multiple_choice') AS multiple_choice_count,\n"
    " (SELECT count(*) FROM question_bank q WHERE q.unit_id=su.id AND q.active=1 "
    "AND q.response_format='code_response') AS code_response_count\n"
    "FROM source_units su;\n"
    "CREATE VIEW quiz_progress AS\n"
    "SELECT s.id AS quiz_id,s.scope_type,s.source_unit_id,s.scope_label,s.state,\n"
    " count(q.id) AS total_questions,\n"
    " coalesce(sum(q.origin='base'),0) AS base_questions,\n"
    " coalesce(sum(q.origin='follow_up'),0) AS follow_up_questions,\n"
    " coalesce(sum(q.state='planned'),0) AS planned_questions,\n"
    " coalesce(sum(q.state='asked'),0) AS asked_questions,\n"
    " coalesce(sum(q.state='deferred'),0) AS deferred_questions,\n"
    " coalesce(sum(q.state='answered'),0) AS answered_questions,\n"
    " coalesce(sum(q.state='retired'),0) AS retired_questions,\n"
    " coalesce(sum(latest.assessment='correct'),0) AS correct_responses,\n"
    " coalesce(sum(latest.assessment='partially_correct'),0) AS partially_correct_responses,\n"
    " coalesce(sum(latest.assessment='incorrect'),0) AS incorrect_responses\n"
    "FROM quiz_sessions s LEFT JOIN quiz_questions q ON q.quiz_id=s.id\n"
    "LEFT JOIN quiz_responses latest ON latest.id=(SELECT r.id FROM quiz_responses r "
    "WHERE r.question_id=q.id ORDER BY r.attempt_number DESC,r.id DESC LIMIT 1)\n"
    "GROUP BY s.id;\n";

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic pop
#endif

static const char *const required_tables[] = {
    "concept_sources",
    "concepts",
    "db_operations",
    "learning_records",
    "metadata",
    "question_bank",
    "question_sources",
    "question_tags",
    "quiz_events",
    "quiz_objectives",
    "quiz_questions",
    "quiz_responses",
    "quiz_sessions",
    "quiz_template_questions",
    "quiz_templates",
    "schema_migrations",
    "source_sections",
    "source_units",
    "tag_aliases",
    "tag_relations",
    "tags",
};

static const char *const required_views[] = {"quiz_progress", "source_coverage", "tag_catalog"};

const char *lbdb_schema_sql(void) { return schema_sql; }

size_t lbdb_schema_sql_size(void) { return strlen(schema_sql); }

const char *const *lbdb_required_tables(size_t *count) {
    *count = sizeof(required_tables) / sizeof(required_tables[0]);
    return required_tables;
}

const char *const *lbdb_required_views(size_t *count) {
    *count = sizeof(required_views) / sizeof(required_views[0]);
    return required_views;
}
